remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
title: GLOBAL MOBILE
description: [GLOBAL MOBILE SALES PREDICTION].
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

